?carbonjiao?2009-09-07 14:51:08??: ??cleanold

diff --git a/repo-tools/cleanold b/repo-tools/cleanold
--- a/repo-tools/cleanold
+++ b/repo-tools/cleanold
@@ -11,7 +11,7 @@ APPNAME=$(basename "${0}")
 cmdline=$@
 
 KEEPN=2
-DIR='/var/cache/pacman/pkg'
+DIR=""
 
 # usage: usage <exitvalue>
 usage ()
@@ -30,36 +30,40 @@ usage ()
 }
 COLORMSG=1
 plain() {
-	local mesg=$1; shift
 	if [ $COLORMSG -eq 1 ]; then
-		printf "\033[1;2m    ${mesg}\033[1;0m\n" "$@" >&2
+		echo -e "\033[1;2m    $@\033[1;0m"
 	else
-		printf "    ${mesg}\n" "$@" >&2
-	fi
-}
-msg() {
-	local mesg=$1; shift
-	if [ $COLORMSG -eq 1 ]; then
-		printf "\033[1;32m==>\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
-	else
-		printf "==> ${mesg}\n" "$@" >&2
+		echo -e "	$@"
 	fi
 }
 
-msg2() {
-	local mesg=$1; shift
+msg() {
 	if [ $COLORMSG -eq 1 ]; then
-		printf "\033[1;34m  ->\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+		echo -e "\033[1;32m==>\033[1;0m\033[1;1m $@\033[1;0m"
 	else
-		printf "  -> ${mesg}\n" "$@" >&2
+		echo -e "==> $@"
+	fi
+}
+msg2() {
+	if [ $COLORMSG -eq 1 ]; then
+		echo -e "\033[1;34m  ->\033[1;0m\033[1;1m $@\033[1;0m"
+	else
+		echo -e "  -> $@"
+	fi
+}
+warn() {
+	if [ $COLORMSG -eq 1 ]; then
+		echo -e "\033[1;33m==> $(gettext "WARN:")\033[1;0m\033[1;1m $@\033[1;0m"
+	else
+		echo -e "==> $(gettext "WARN:") $@"
 	fi
 }
 error() {
 	local mesg=$1; shift
 	if [ $COLORMSG -eq 1 ]; then
-		printf "\033[1;31m==> $(gettext "ERROR:")\033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+		echo -e "\033[1;31m==> $(gettext "ERROR:")\033[1;0m\033[1;1m $@\033[1;0m"
 	else
-		printf "==> $(gettext "ERROR:") ${mesg}\n" "$@" >&2
+		echo -e "==> $(gettext "ERROR:") $@"
 	fi
 }
 
@@ -77,11 +81,21 @@ while getopts 'f:a:n:r:h:?' arg; do
    esac
 done
 
+if [ "x$DIR" = "x" ]; then
+	if [ ! -f /etc/pacman.conf ]; then error "没有指定预清理的目录，且操作系统不是Arch，为安全考虑，程序退出！" && usage 1; fi
+	DIR=$(grep CacheDir /etc/pacman.conf | awk '{print $3}')
+	if [ "x$DIR" = "x" ]; then error "没有指定预清理的目录，且pacman.conf无缓存相关设置!" && usage 1; fi
+fi
+
 msg "输入的参数:$cmdline"
-result="清理目录$DIR, 保留$KEEPN个版本"
-case $cmdline in *-a*) result="${result}, 删除系统没有安装的软件包";; esac
+result="清理目录$DIR, 保留${KEEPN}个版本"
+case $cmdline in *-a*) result="${result}, 删除系统没有安装的软件包"
+			if [ ! -f /etc/pacman.conf ]; then error "操作系统不是Arch, 出现问题后果自负！"; fi
+			;;
+		esac
 case $cmdline in *-f*) result="${result}, 删除先无需确认";; esac
-msg $result
+
+msg ${result}
 
 shift `expr $OPTIND - 1`
 
@@ -100,10 +114,11 @@ for ((i=0; i<${#list[@]}; i++)); do
 
 	case $cmdline in *-a*)
 		# 如果系统里没有安装此包，将其删除
-		if ! pacman -Qq $pkgname>/dev/null 2>&1; then
+		#if ! pacman -Qq $pkgname>/dev/null 2>&1; then  #不喜欢调用pacman的用如下语句 Carbonjiao注
+		if [ "x$(ls $(grep DBPath /etc/pacman.conf | awk '{print $3}')/local | grep "${list[$i]// /-}")" = "x" ]; then
 			plain "系统中没有安装$pkgname, 现在删除$DIR 下的软件包 ${list[$i]// /-}"
 			case $cmdline in *-f*) rm -rf ${list[$i]// /-};;
-					  *) rm -ri ${list[$i]// /-} ;; 
+				  *) rm -ri ${list[$i]// /-} ;; 
 			esac
 			continue
 		fi
